```
import numpy as np
data = np.loadtxt('wine.csv')


so basically when we use our training loop what we do is we run our training for multiple epoch and at each epoch
we divide our dataset in batches and run our training for each batch


for epoch in range(1000):
   ----loop over all batches
  for i in range(total_batches):
    x_batch, y_batch =....
```

We can do the same using dataset and dataloader in pytorch

epoch = 1 forward and backward pass of All training samples

batch_size = number of training samples in one forward & backward pass

number of iterations = number of passes , each pass using [batch_size] number of samples

e.g 100 samples , batch_size =20 --> 100/20 = 5 iterations for 1 epoch

In [41]:
import torch
import torchvision
from torch.utils.data import Dataset, DataLoader
import numpy as np
import math

In [42]:

class WineDataset(Dataset):
  def __init__(self):
    # data loading
    xy = np.loadtxt('https://raw.githubusercontent.com/python-engineer/pytorchTutorial/master/data/wine/wine.csv', delimiter=",", dtype=np.float32, skiprows=1)
    self.x = torch.from_numpy(xy[:,1:])
    self.y = torch.from_numpy(xy[:,[0]]) # n_samples * 1
    self.n_samples = xy.shape[0]
    
  def __getitem__(self, index):
    return self.x[index], self.y[index]

  def __len__(self):
    #len(dataset)
    return self.n_samples


dataset = WineDataset()

# first_data = dataset[0]

# feature, labels  = first_data

# print(feature, labels)

# USING DATALOADER FOR GETTING THE DATASET

dataloader = DataLoader(dataset= dataset, batch_size=4, shuffle=True, num_workers=2)

dataiter = iter(dataloader)

data = dataiter.next()

features, labels = data

print(features, labels)

tensor([[1.2960e+01, 3.4500e+00, 2.3500e+00, 1.8500e+01, 1.0600e+02, 1.3900e+00,
         7.0000e-01, 4.0000e-01, 9.4000e-01, 5.2800e+00, 6.8000e-01, 1.7500e+00,
         6.7500e+02],
        [1.2370e+01, 1.1700e+00, 1.9200e+00, 1.9600e+01, 7.8000e+01, 2.1100e+00,
         2.0000e+00, 2.7000e-01, 1.0400e+00, 4.6800e+00, 1.1200e+00, 3.4800e+00,
         5.1000e+02],
        [1.2770e+01, 3.4300e+00, 1.9800e+00, 1.6000e+01, 8.0000e+01, 1.6300e+00,
         1.2500e+00, 4.3000e-01, 8.3000e-01, 3.4000e+00, 7.0000e-01, 2.1200e+00,
         3.7200e+02],
        [1.3720e+01, 1.4300e+00, 2.5000e+00, 1.6700e+01, 1.0800e+02, 3.4000e+00,
         3.6700e+00, 1.9000e-01, 2.0400e+00, 6.8000e+00, 8.9000e-01, 2.8700e+00,
         1.2850e+03]]) tensor([[3.],
        [2.],
        [2.],
        [1.]])


In [43]:
# DUMMY TRAINNING LOOP
class WineDataset(Dataset):
  def __init__(self):
    # data loading
    xy = np.loadtxt('https://raw.githubusercontent.com/python-engineer/pytorchTutorial/master/data/wine/wine.csv', delimiter=",", dtype=np.float32, skiprows=1)
    self.x = torch.from_numpy(xy[:,1:])
    self.y = torch.from_numpy(xy[:,[0]]) # n_samples * 1
    self.n_samples = xy.shape[0]
    
  def __getitem__(self, index):
    return self.x[index], self.y[index]

  def __len__(self):
    #len(dataset)
    return self.n_samples


dataset = WineDataset()

# first_data = dataset[0]

# feature, labels  = first_data

# print(feature, labels)

# USING DATALOADER FOR GETTING THE DATASET

dataloader = DataLoader(dataset= dataset, batch_size=4, shuffle=True, num_workers=2)

# dataiter = iter(dataloader)

# data = dataiter.next()

# features, labels = data

# print(features, labels)

num_epoch = 2
total_samples = len(dataset)

n_iterations = math.ceil(total_samples/4)

print(total_samples, n_iterations)


for epoch in range(num_epoch):
  for i,(inputs,labels) in enumerate(dataloader):
    # forward and backward pass and upadte weights

    if((i+1) % 5 ==0):
      print(f'epoch{epoch+1}/{num_epoch}, step{i+1}/{n_iterations}, inputs {inputs.shape}')


# torchvision.datasets.MNIST()

178 45
epoch1/2, step5/45, inputs torch.Size([4, 13])
epoch1/2, step10/45, inputs torch.Size([4, 13])
epoch1/2, step15/45, inputs torch.Size([4, 13])
epoch1/2, step20/45, inputs torch.Size([4, 13])
epoch1/2, step25/45, inputs torch.Size([4, 13])
epoch1/2, step30/45, inputs torch.Size([4, 13])
epoch1/2, step35/45, inputs torch.Size([4, 13])
epoch1/2, step40/45, inputs torch.Size([4, 13])
epoch1/2, step45/45, inputs torch.Size([2, 13])
epoch2/2, step5/45, inputs torch.Size([4, 13])
epoch2/2, step10/45, inputs torch.Size([4, 13])
epoch2/2, step15/45, inputs torch.Size([4, 13])
epoch2/2, step20/45, inputs torch.Size([4, 13])
epoch2/2, step25/45, inputs torch.Size([4, 13])
epoch2/2, step30/45, inputs torch.Size([4, 13])
epoch2/2, step35/45, inputs torch.Size([4, 13])
epoch2/2, step40/45, inputs torch.Size([4, 13])
epoch2/2, step45/45, inputs torch.Size([2, 13])


# TRANSFORM IN DATASET

In [44]:
# tranforms built in mnist datset numpy to tenosrs
dataset = torchvision.datasets.MNIST(download = True, root='./data', transform=torchvision.transforms.ToTensor())

In [45]:
# Writing our own tranform classes

# DUMMY TRAINNING LOOP
class WineDataset(Dataset):
  def __init__(self, transform=None):
    # data loading
    xy = np.loadtxt('https://raw.githubusercontent.com/python-engineer/pytorchTutorial/master/data/wine/wine.csv', delimiter=",", dtype=np.float32, skiprows=1)
    
    # here explicitly we did tranform from numpy array to transform
    # self.x = torch.from_numpy(xy[:,1:])
    # self.y = torch.from_numpy(xy[:,[0]]) # n_samples * 1

    self.x = xy[:, 1:]
    self.y = xy[:,[0]]

    self.n_samples = xy.shape[0]
    self.transform = transform


  def __getitem__(self, index):
    sample = self.x[index], self.y[index]

    if self.transform:
      sample = self.transform(sample)

    return sample

  def __len__(self):
    #len(dataset)
    return self.n_samples

class ToTensor():
  def __call__(self, sample):
    
    inputs, targets = sample
    return torch.from_numpy(inputs), torch.from_numpy(targets)


class MulTransform():
  def __init__(self, factor) -> None:
    self.factor = factor

  def __call__(self, sample):
    inputs, targets = sample
    inputs *= self.factor
    return inputs, sample

# dataset = WineDataset(transform = None)
dataset = WineDataset(transform = ToTensor())
first_data = dataset[0]
featurs, labels = first_data
print(features)
print(type(features), type(labels))


# To apply sequence of transforms using composed transforms
composed = torchvision.transforms.Compose([ToTensor(), MulTransform(2)])
dataset = WineDataset(transform = composed)
first_data = dataset[0]
features, labels = first_data
print(features)
print(type(features), type(labels))

tensor([[1.2960e+01, 3.4500e+00, 2.3500e+00, 1.8500e+01, 1.0600e+02, 1.3900e+00,
         7.0000e-01, 4.0000e-01, 9.4000e-01, 5.2800e+00, 6.8000e-01, 1.7500e+00,
         6.7500e+02],
        [1.2370e+01, 1.1700e+00, 1.9200e+00, 1.9600e+01, 7.8000e+01, 2.1100e+00,
         2.0000e+00, 2.7000e-01, 1.0400e+00, 4.6800e+00, 1.1200e+00, 3.4800e+00,
         5.1000e+02],
        [1.2770e+01, 3.4300e+00, 1.9800e+00, 1.6000e+01, 8.0000e+01, 1.6300e+00,
         1.2500e+00, 4.3000e-01, 8.3000e-01, 3.4000e+00, 7.0000e-01, 2.1200e+00,
         3.7200e+02],
        [1.3720e+01, 1.4300e+00, 2.5000e+00, 1.6700e+01, 1.0800e+02, 3.4000e+00,
         3.6700e+00, 1.9000e-01, 2.0400e+00, 6.8000e+00, 8.9000e-01, 2.8700e+00,
         1.2850e+03]])
<class 'torch.Tensor'> <class 'torch.Tensor'>
tensor([2.8460e+01, 3.4200e+00, 4.8600e+00, 3.1200e+01, 2.5400e+02, 5.6000e+00,
        6.1200e+00, 5.6000e-01, 4.5800e+00, 1.1280e+01, 2.0800e+00, 7.8400e+00,
        2.1300e+03])
<class 'torch.Tensor'> <class 'tuple